### ISSUE TITLE
Hide titles if the tags mode is enabled

### ISSUE THREAD

**Issue by UlisesGascon** [UlisesGascon/openssf-scorecard-monitor#31]
If the user uses `report-tags-enabled=true` then titles should not be included in the markdown report file:

For reference this are the titles:
```
# OpenSSF Scorecard Report

## Summary
```

Side note: This won't affect issues template

**Comment by KoolTheba** [comment]
I'd love to help with this issue! 🖐️
I'll create the PR soon!
