### ISSUE TITLE
Show the scorecard badges in the table

### ISSUE THREAD

**Issue by rajbos** [UlisesGascon/openssf-scorecard-monitor#45]
I'd like to show the information in the table with a badge similar to what I have done in my org readme [here](https://github.com/devops-actions?view_as=public):

![image](https://user-images.githubusercontent.com/6085745/226470391-42dcf2b2-1545-4f0c-915c-e95fb4e7fdfd.png)

Setup is like this:
`[![OpenSSF Scorecard](https://api.securityscorecards.dev/projects/github.com/devops-actions/issue-comment-tag/badge)](https://api.securityscorecards.dev/projects/github.com/devops-actions/issue-comment-tag)`

**Comment by UlisesGascon** [comment]
**I like the idea!**

I think we can implement this with an opcional flag like `render-badge`. If the flag is positive then in the templates we can replace the pure number in the `Score` column for the badge.

**Comment by UlisesGascon** [comment]
Do you want to help with the implementation?

**Comment by rajbos** [comment]
@UlisesGascon: yes! I'll try to setup a concept for it.

**Comment by rajbos** [comment]
Working on it [here](https://github.com/rajbos/openssf-scorecard-monitor/actions/runs/4519255832). Does `deps.dev` have badges as well? If so I'll make the url variable up front.

![image](https://user-images.githubusercontent.com/6085745/227718858-8bdaa6e2-3732-4893-8cb7-29a8d7229cf5.png)

**Comment by UlisesGascon** [comment]
Seems super good! As far I know `deps.dev` doesn't have badges so we can ignore it 👍
