### ISSUE TITLE
Clarify Scorecard requirements in docs

### ISSUE THREAD

**Issue by lelia** [UlisesGascon/openssf-scorecard-monitor#67]
We've recently been exploring the use of OpenSSF Scorecard Monitor for our various open source organizations, but hit a roadbump after finding that Scorecard Monitor was only discovering a handful of repositories in our orgs (regardless of which projects were listed in `scope.json`). 

After some investigation, I realized that OpenSSF was [automatically tracking](https://github.com/ossf/scorecard/blob/main/docs/faq.md#can-i-preview-my-projects-score) a select group of our projects upstream, which is why some projects already scores and others didn't. I'd like to update the README docs to clarify these requirements, and provide some hints in case others experience similar issues.

**Comment by UlisesGascon** [comment]
I am super interested in getting feedback about the tool also in providing support to extend the adoption in open source organizations. Let me know if you are available for a quick chat 🙂

**Comment by lelia** [comment]
> I am super interested in getting feedback about the tool also in providing support to extend the adoption in open source organizations. Let me know if you are available for a quick chat 🙂

@UlisesGascon That would be great! I'll try pinging you on OpenSSF Slack and we can go from there 🙌

**Comment by UlisesGascon** [comment]
Great! Thanks a lot :)
